=== epsonavy/WebSheets/sheet.dtd
<?xml version = "1.0" encoding ="utf-8" ?>
<!-- sheet.dtd  -->
<!ELEMENT sheet (row+) >
<!ELEMENT row (data+) >
<!ELEMENT data (#PCDATA)>
<!ATTLIST sheet name CDATA #REQUIRED >

=== epsonavy/WebSheets/sheet.xml
<?xml version='1.0' encoding='UTF-8'?>
        <!DOCTYPE sheet SYSTEM 'sheet.dtd' >
        <sheet name='test1'><row><data>A1</data><data></data><data>B1</data><data>C1</data></row><row><data>A1</data><data></data><data>B1</data><data>C1</data><data>A2</data><data></data><data>B2</data><data>C2</data></row><row><data>A1</data><data></data><data>B1</data><data>C1</data><data>A2</data><data></data><data>B2</data><data>C2</data><data></data><data></data><data></data><data></data></row></sheet>
